DATASET:
  root_dataset: "./data/"
  list_train: "./data/apartment_0_training.odgt"  # apartment_0
  list_val: "./data/hw1_validation.odgt"  # habitat_validation, apartment_0_validation, hw1_validation
  num_class: 150  #1st: 150, then: 101
  imgSizes: (300, 375, 450, 525, 600)
  imgMaxSize: 1000
  padding_constant: 8
  segm_downsampling_rate: 8
  random_flip: True

MODEL:
  arch_encoder: "resnet50dilated"
  arch_decoder: "ppm_deepsup"
  # weights_encoder: "ckpt/encoder_epoch_20.pth"
  # weights_decoder: "ckpt/decoder_epoch_20.pth"
  fc_dim: 2048


TRAIN:
  batch_size_per_gpu: 2
  num_epoch: 60  # 20
  start_epoch: 20  # 0
  epoch_iters: 2000 # 5000
  optim: "SGD"  # SGD, Adam
  lr_encoder: 3e-2  # 0.02
  lr_decoder: 3e-2  # 0.02
  lr_pow: 0.8
  beta1: 0.9
  beta2: 0.999
  weight_decay: 1e-5
  deep_sup_scale: 0.1
  fix_bn: False  #False
  workers: 16
  disp_iter: 40
  seed: 304

VAL:
  visualize: True  # False
  checkpoint: "epoch_42.pth"  # apartment: 19:39=Mean IoU: 0.3624, Accuracy: 85.29%

TEST:
  checkpoint: "epoch_40.pth"  # 20
  result: "./"

DIR: "ckpt/habitat-resnet50/train-21_apartment0-2600-SGD"
