DATASET:
  root_dataset: "./data/"
  list_train: "./data/habitat_training.odgt"  # apartment_0_training, habitat_training
  list_val: "./data/hw1_2nd_validation.odgt"  # habitat_validation, apartment_0_validation, hw1_validation, hw1_2nd_validation
  num_class: 150  # 150, 101
  imgSizes: (300, 375, 450, 525, 600)
  imgMaxSize: 1000
  padding_constant: 8
  segm_downsampling_rate: 8
  random_flip: True

MODEL:
  arch_encoder: "resnet50dilated"
  arch_decoder: "ppm_deepsup"
  fc_dim: 2048  # 2048

TRAIN:
  batch_size_per_gpu: 2
  num_epoch: 40  # 20
  start_epoch: 20
  epoch_iters: 2000 # 5000
  optim: "SGD"  # SGD
  lr_encoder: 1e-2  # 0.02
  lr_decoder: 1e-2  # 0.02
  lr_pow: 0.9
  beta1: 0.9
  beta2: 0.999
  weight_decay: 1e-5  # 1e-5
  deep_sup_scale: 0.1  # 0.1
  fix_bn: False  #False
  workers: 16
  disp_iter: 20
  seed: 203

VAL:
  visualize: True  # False
  checkpoint: "epoch_33.pth"  # habitat: 18:33=55.90

TEST:
  checkpoint: "epoch_40.pth"  # 20
  result: "./test/semantic"

DIR: "ckpt/habitat-resnet50/train-18_habitat-2600-SGD"
